### ISSUE TITLE
Queries do not use `table` param from `DoxModel`

### ISSUE THREAD

**Issue by andyhorn** [dartondox/dox-query-builder#22]
If I create a model using the `DoxModel` annotation and set a custom `table` name, the SQL query _does not_ use this value and uses the name of the model instead.

**Model Definition**
```dart
// Set custom table name to "blogs"
@DoxModel(table: 'blogs')
class Blog extends BlogGenerator {
  @Column()
  String? name;

  @Column()
  String? content;
}
```

**Migration**
```dart
// Create a "blogs" table in my Postgres DB
Future<void> up() async {
  await Schema.create('blogs', (Table table) {
    table.id();
    table.string('name');
    table.string('content');
    table.timestamps();
  });
}

Future<void> down() async {
  await Schema.drop('blogs');
}
```

**Usage**
```dart
class BlogController {
  Future<List<Blog>> index(DoxRequest request) async {
    final blogs = await Blog().get();
    return blogs;
  }
}
```

When I hit the `api/blogs` endpoint, the server throws an error like:
```
PostgreSQLSeverity.error 42P01: relation "blog" does not exist
```

According to the [docs](https://www.dartondox.dev/database/model#table-name), setting the custom table name should allow me to use a `blogs` table.

**Comment by necessarylion** [comment]
@andyhorn please update dox_builder to `^1.0.1`. 

Issue have been fixed here https://github.com/dartondox/dox_builder/commit/6fca899338d669297bb238f073755d066313f9be

**Comment by andyhorn** [comment]
@necessarylion Fantastic, thank you 👍
